### ISSUE TITLE
Java Exception during shutdown, if Bluetooth service does not exist

### ISSUE THREAD

**Issue by speed-axel** [kflog-project/Cumulus#31]
If Cumulus is shutdown on Android and the decice provides no Bluetooth service, a java exception is thrown.

Caused by: java.lang.IllegalArgumentException: Receiver not registered: org.kflog.cumulus.CumulusActivity$2@41cee830
at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:667)
at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1575)
at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:489)
at org.kflog.cumulus.CumulusActivity.onDestroy(CumulusActivity.java:1124)
at android.app.Activity.performDestroy(Activity.java:5515)
at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1119)
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3715)

**Comment by speed-axel** [comment]
That bug was fixed. BTW there was found another bug which occurred during stop of BT connection. It was fixed too.
